### ISSUE TITLE
Error while calling lua chunk

### ISSUE THREAD

**Issue by FrancisCode13** [ellisonleao/gruvbox.nvim#65]
![imagen](https://user-images.githubusercontent.com/77551844/132110117-b8c905f7-7fd5-42a5-9060-a4acb62d9c81.png)
I was making my own Neovim config, and when installing gruvbox and setting it as a theme, when I open neovim, I get this message.

**Comment by ellisonleao** [comment]
what neovim version are you using?

**Comment by FrancisCode13** [comment]
> 
> 
> what neovim version are you using?

![imagen](https://user-images.githubusercontent.com/77551844/132130842-a54d4d2a-0045-4afa-9135-eefae780acd8.png)

Nvim v0.4.4

**Comment by ellisonleao** [comment]
@FrancisCode13  `vim.g` is not available for that version so the plugin will only work for 0.5+ versions

**Comment by FrancisCode13** [comment]
Ok ok, i understand, and a question, how i can update neovim?
i was trying with choco upgrade neovim --pre
And other but that don't run

**Comment by ellisonleao** [comment]
Unfortunately i am not sure how to fix that on windows. Maybe you can check the issues in the neovim project to see if others have faced the same issue as you or maybe you can try follow other [installation approaches](https://github.com/neovim/neovim/wiki/Installing-Neovim#windows) . I am closing this issue since its not related to the plugin.
