### ISSUE TITLE
Deprecate and remove airline

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/gruvbox.nvim#95]
Seems like airline is not used anymore by the majority of neovim users and it's the only remaining leftover for vimscript code. I am considering removing it and leaving just lightline as a custom option for now. I would like to hear some thoughts before moving on

**Comment by sQVe** [comment]
I think this makes sense, keep things as lightweight ad possible. If you want to use airline then you could use the original gruvbox instead.

**Comment by darkangel-ua** [comment]
I'm using `airline` and I don't want to use `lightline` and spend a month trying to integrate all useful stuff into it. Do not really understand what is wrong with supporting it. It's absolutely the same as you support `telescope` or any other plugins except it requires to use vimscript instead of highlight groups - not that nice and clean, but still the same way conceptually. Would be nice it `airline` uses highlight groups also, it isn't that is life :)

**Comment by ellisonleao** [comment]
hey @darkangel-ua i believe if you switch to a more modern statusline plugin like lightline or even [lualine](https://github.com/nvim-lualine/lualine.nvim) you will feel a lot better and definitely won't spend 1 month configuring it because they are really straightforward.  Seems that the majority of people using this particular repo are not using airline for their statusline plugin and i really want to make this plugin as lean as possible so i am probably moving forward with the change in the next few days

**Comment by roland-rollo** [comment]
I still voting for removing airline.

**Comment by darkangel-ua** [comment]
I have moved to `lualine` and it's looking good.
